---
version: "3.3"
services:
  prometheus:
    hostname: prometheus
    image: prom/prometheus:v2.7.1
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    links:
      - azure-exporter

  azure-exporter:
    hostname: azure-exporter
    image: mujx/azure-exporter
    ports:
      - "3000:3000"
    entrypoint:
      - "/app/bin/azure-exporter"
      - "--config-file"
      - "/etc/config.yaml"
    volumes:
      - "./config.yaml:/etc/config.yaml"
    environment:
      - "ENV=dev"
      - "AZURE_CLIENT_SECRET=$AZURE_CLIENT_SECRET"
