global:
  scrape_interval:     40s
  scrape_timeout:      10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'azure-exporter'
    static_configs:
      - targets: ['azure-exporter:3000']
